version: 2
updates:
  # Update Python packages weekly.
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"

  # Update GitHub Actions monthly.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
