name: "Validate PR title"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  validate-pr-title:
    uses: rungalileo/.github/.github/workflows/validate-pr-title.yaml@main
