import { publicPrefixWitnesses, publicPrefixRule as rule, publicCheckpoint as check, witnessCommand as command,
  type PublicPrefixWitnessRule } from "./public-prefix-witnesses.js";

const init = command("init");
const policy = (choice: number) => command("policy", choice);
const begin = (choice: number) => command("beginCall", choice);
const seed = (choice: number) => command("seed", choice);
const resolve = (choice: number) => command("resolveLoader", choice);
const advance = (ms: number) => command("advance", ms);
const dump = command("releaseDump", 0), write = command("releaseWrite", 0);
// A schedule alone cannot earn a witness. Each rule requires public outcomes at
// its distinguishing boundary, often before and after a probe. These are exact
// replayable prefixes, independent of filenames and private model cache state.
export const shadowLayersWitnessRules: readonly PublicPrefixWitnessRule[] = [
  rule("dark-local-source-publication-stops-later-shadow", "darkSourcePublishesLocalBeforeShadowWriteTest",
    [init, policy(2), begin(9), resolve(1), policy(12), begin(9)],
    check(3, { calls: [1], dumps: 1, writes: 0 }),
    check(5, { calls: [1, 1], loaders: 1, reads: 1, dumps: 1, writes: 0, shadow: [] })),
  rule("dark-request-source-publication-is-scope-local", "darkSourcePublishesRequestBeforeShadowWriteTest",
    [init, policy(1), begin(0), resolve(1), policy(12), begin(0), policy(1), begin(3)],
    check(5, { calls: [1, 1], loaders: 1, reads: 1, dumps: 1, writes: 0, shadow: [] }),
    check(7, { calls: [1, 1, 0], loaders: 2, reads: 1, shadow: ["dropped"] })),
  rule("dark-present-c0-never-publishes-local", "darkPresentC0NeverBecomesLocalPublicationTest",
    [init, policy(2), seed(0), begin(9), begin(9), resolve(2), policy(12), begin(9)],
    check(4, { calls: [0, 0], loaders: 2, reads: 1, loads: 0, shadow: ["dropped"] }),
    check(7, { calls: [2, 0, 2], loaders: 2, reads: 2, loads: 1, writes: 0, shadow: ["dropped", "mismatch"] })),
  rule("dark-present-c0-never-publishes-request", "darkPresentC0NeverBecomesRequestPublicationTest",
    [init, policy(1), seed(0), begin(0), begin(0), resolve(2), policy(12), begin(0), policy(1), begin(3)],
    check(4, { calls: [0, 0], loaders: 2, reads: 1, loads: 0, shadow: ["dropped"] }),
    check(7, { calls: [2, 0, 2], loaders: 2, reads: 2, writes: 0 }),
    check(9, { calls: [2, 0, 2, 0], loaders: 3, reads: 3, writes: 0 })),
  rule("dark-job-dedup-preserves-independent-source-values", "deduplicatedJobKeepsIndependentCallerSourcesTest",
    [init, policy(3), begin(9), begin(9), resolve(4), resolve(1), dump, write, policy(5), begin(9)],
    check(3, { calls: [0, 0], loaders: 2, reads: 1, shadow: ["dropped"] }),
    check(4, { calls: [0, 2], dumps: 0, writes: 0 }),
    check(9, { calls: [1, 2, 1], loaders: 2, reads: 2, loads: 1, writes: 1, shadow: ["dropped", "filled"] })),
  rule("dark-eligible-stale-c0-never-recovers", "darkFailureDoesNotUseEligibleStaleBytesTest",
    [init, policy(3), seed(3), begin(9), command("rejectLoader", 0)],
    check(4, { calls: [3], loaders: 1, reads: 1, loads: 0, dumps: 0, writes: 0,
      classifications: 0, recovery: [], shadow: ["source_error"] })),
  rule("invalid-dark-shadow-preserves-local-source-publication", "invalidShadowKeepsLocalPublicationTest",
    [init, policy(7), begin(9), resolve(1), policy(12), begin(9)],
    check(5, { calls: [1, 1], loaders: 1, reads: 0, dumps: 0, writes: 0, shadow: [] })),
  rule("unbounded-caller-outlives-released-dark-job", "unboundedCallerSurvivesDarkJobDeadlineTest",
    [init, policy(3), begin(9), advance(60_000), begin(9), resolve(1), resolve(4)],
    check(3, { calls: [0], loaders: 1, reads: 1, shadow: ["timeout"] }),
    check(4, { calls: [0, 0], loaders: 2, reads: 2, shadow: ["timeout"] }),
    check(5, { calls: [1, 0], dumps: 0 }),
    check(6, { calls: [1, 2], dumps: 1, writes: 0, shadow: ["timeout"] })),
  rule("mixed-shadow-capacity-retains-only-owned-source", "servedAndDarkJobsShareCapacityButNotSourceOwnershipTest",
    [init, seed(0), policy(4), begin(9), policy(3), begin(10), begin(11), advance(60_000),
      begin(11), begin(10), resolve(2), begin(10), resolve(4)],
    check(6, { calls: [1, 0, 0], loaders: 3, reads: 2, shadow: ["dropped"] }),
    check(8, { loaders: 4, reads: 3, shadow: ["dropped", "timeout", "timeout"] }),
    check(9, { loaders: 5, reads: 3, shadow: ["dropped", "timeout", "timeout", "dropped"] }),
    check(11, { loaders: 6, reads: 4, shadow: ["dropped", "timeout", "timeout", "dropped"] }),
    check(12, { calls: [1, 2, 0, 0, 0, 0], loads: 1, dumps: 0, writes: 0,
      sourceScopes: [false, true, true, true, true, true] })),
  rule("mixed-shadow-capacity-is-per-instance", "fullMixedInstanceDoesNotBlockAnotherInstanceTest",
    [init, seed(0), policy(4), begin(9), policy(3), begin(10), begin(11), begin(14)],
    check(6, { loaders: 3, reads: 2, shadow: ["dropped"] }),
    check(7, { calls: [1, 0, 0, 0], loaders: 4, reads: 3,
      sourceScopes: [false, true, true, true], shadow: ["dropped"] })),
  rule("served-diagnostic-source-never-publishes-local", "servedDiagnosticSourceDoesNotPopulateLocalTest",
    [init, seed(0), policy(4), begin(9), resolve(2), policy(2), begin(9)],
    check(4, { calls: [1], writes: 0, shadow: ["mismatch"] }),
    check(6, { calls: [1, 0], loaders: 2, reads: 3, writes: 0,
      sourceScopes: [false, true], shadow: ["mismatch"] })),
  rule("validated-remote-hit-warms-local-and-stops-shadow", "validatedRemoteHitStopsFurtherShadowTest",
    [init, seed(0), policy(12), begin(9), begin(9), resolve(2), begin(9)],
    check(4, { calls: [1, 1], loaders: 1, reads: 1, loads: 1, shadow: [] }),
    check(6, { calls: [1, 1, 1], loaders: 1, reads: 2, writes: 0, shadow: ["mismatch"] })),
  rule("ordinary-serving-miss-has-no-diagnostic-source", "ordinaryServingMissDoesNotAdmitDiagnosticSourceTest",
    [init, policy(4), begin(9), resolve(2), dump, write, policy(5), begin(9)],
    check(2, { calls: [0], loaders: 1, reads: 1, sourceScopes: [true], shadow: [] }),
    check(7, { calls: [2, 2], loaders: 1, reads: 2, dumps: 1, writes: 1, shadow: [] })),
  rule("shadow-cohort-below-does-not-admit", "shadowCohortBelowDoesNotAdmitTest",
    [init, policy(9), begin(9), resolve(1)],
    check(3, { calls: [1], loaders: 1, reads: 0, dumps: 0, writes: 0, shadow: [] })),
  rule("shadow-cohort-equality-does-not-admit", "shadowCohortEqualityDoesNotAdmitTest",
    [init, policy(10), begin(9), resolve(1)],
    check(3, { calls: [1], loaders: 1, reads: 0, dumps: 0, writes: 0, shadow: [] })),
  rule("shadow-cohort-above-admits", "shadowCohortAboveAdmitsTest",
    [init, policy(11), begin(9), resolve(1)],
    check(3, { calls: [1], loaders: 1, reads: 1, dumps: 1, writes: 0, shadow: [] })),
  rule("dark-fill-policy-snapshot-controls-physical-expiry", "darkFillRetainsPolicyThroughSerializationTest",
    [init, policy(3), begin(9), policy(8), resolve(1), policy(13), dump, write,
      advance(120_000), policy(13), begin(9), command("rejectLoader", 1)],
    check(4, { calls: [1], dumps: 1, writes: 0 }),
    check(7, { writes: 1, writeTtls: [120_000], shadow: ["filled"] }),
    check(11, { calls: [1, 3], loaders: 2, reads: 2, loads: 0, writes: 1,
      classifications: 1, recovery: ["miss"] })),
  rule("retained-fresh-c0-compares-after-freshness-boundary", "retainedFreshC0StillComparesAfterFreshnessBoundaryTest",
    [init, policy(3), seed(2), begin(9), advance(1), resolve(2)],
    check(4, { calls: [0], reads: 1, loads: 0, shadow: [] }),
    check(5, { calls: [2], loaders: 1, reads: 2, loads: 1, dumps: 0, writes: 0, shadow: ["mismatch"] })),
  rule("expired-c0-miss-fills-source-and-serves-probe", "expiredC0CanFillAndServeNewValueTest",
    [init, policy(3), seed(3), begin(9), resolve(2), dump, write, policy(5), begin(9)],
    check(4, { calls: [2], reads: 1, loads: 0, dumps: 1 }),
    check(8, { calls: [2, 2], loaders: 1, reads: 2, loads: 1, writes: 1, shadow: ["filled"] })),
  rule("acquired-c0-miss-does-not-reread-before-fill", "acquiredMissDoesNotRereadBeforeFillTest",
    [init, policy(3), begin(9), seed(0), resolve(2), dump, write, policy(5), begin(9)],
    check(6, { calls: [2], reads: 1, loads: 0, writes: 1, shadow: ["filled"] }),
    check(8, { calls: [2, 2], loaders: 1, reads: 2, loads: 1, writes: 1 })),
  rule("dark-propagated-timeout-is-source-error", "darkPropagatedTimeoutIsSourceFailureTest",
    [init, policy(3), begin(9), command("rejectTimeout", 0)],
    check(3, { calls: [3], loaders: 1, classifications: 0, recovery: [],
      sourceScopes: [true], dumps: 0, writes: 0, shadow: ["source_error"] })),
  rule("served-propagated-timeout-preserves-hit", "servedPropagatedTimeoutPreservesHitTest",
    [init, seed(0), policy(4), begin(9), command("rejectTimeout", 0)],
    check(4, { calls: [1], loaders: 1, sourceScopes: [false], dumps: 0, writes: 0, shadow: ["source_error"] })),
];

export function shadowLayersWitnesses(paths: readonly string[]): Set<string> {
  return publicPrefixWitnesses(paths, shadowLayersWitnessRules);
}
